VotingSite/VotingSite/Controllers/ReviewBallotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VotingSite.Controllers
{
    public class ReviewBallotController : Controller
    {
        // GET: ReviewBallot
        public ActionResult Index()
        {
            return View();
        }
    }
}

VotingSite/VotingSite/Views/Shared/_LandAndVoteLayout.cshtml
@model VotingSite.UiDependentModels.LandingPgViewModel

@using VotingSite.UiDependentModels

@{
    var viewModel = @Model;     //(LandingPgViewModel)ViewBag.LandingPgViewModel;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TEST TITLE OF PAGE HERE.</title>

    @Styles.Render("~/Content/landAndVote") @* replaces the "/Content/css" bundle *@
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
<div class="lav-page-container" id="landAndVoteWrapper">

    <div class="elect-toolbar top">
        <div class="toolbar-background"></div>
        <div class="toolbar-content">
            <div class="election-info">
                <div class="election-title">@viewModel.ElectionName</div>
            </div>
            <div class="elect-actions">
                <div class="elect-action">
                    <a class="action-button">
                        <img src="~/Content/icons/action/settings.svg" class="elect-action-icon" alt="Gear Icon" />
                        <span class="action-text">Settings</span>
                    </a>
                </div>
                <div class="elect-action">
                    <a class="action-button">
                        <img src="~/Content/icons/action/help-solid.svg" class="elect-action-icon" alt="Question mark icon" />
                        <span class="action-text">Help</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
        
    <div class="lav-under-toolbar-container">

        @* Sidebar -- contest-summary.component.html *@
        <div class="lav-sidebar-container sidebar">

            <div class="sidebar-header-container no-select">
                <div class="sidebar-title-text">
                    My Ballot
                </div>
                <div class="sidebar-progress">
                    @*<div class="contest-summary-selected">*@
                    @viewModel.BallotData.Contests.Count(x => x.VotesCast >= 1) / @viewModel.BallotData.TotalContests Completed
                </div>

                <div class="sidebar-message-text">
                    To vote on a position or change a selection, select a position's title below.
                </div>
            </div>

            <div class="scroll-content">
                <div class="summary-contests">
                    <div class="contest-summary-text no-select">
                        @foreach (var contest in @Model.BallotData.Contests.OrderBy(ob => ob.SortOrder))
                        {
                            <!-- was: class="list-group-item list-group-item-action bg-light" -->
                                @*<a id="@contest.HtmlContestId" href="#" class="list-group-item list-group-item-action bg-light">@contest.Title</a>*@
                            <a id="@contest.HtmlContestId" href="#" class="contest-summary-title">
                                @contest.Title
                                <span class="contest-limit">
                                    @contest.VotesCast / @contest.MaxVotes
                                </span>
                            </a>
                        }
                    </div>
                </div>
                @* end of sidebar *@
            </div>

            <div class="column-filler"></div>

            <div class="elect-toolbar bottom">
                <div class="toolbar-background"></div>
                <div class="toolbar-content">
                    <div class="elect-action">
                        @* [routerLink]="['/ballot', 'review']" *@
                        <a class="action-button" href="@Url.Action("Index", "ReviewBallot")">
                            <span class="action-text">REVIEW MY BALLOT</span>
                        </a>
                    </div>
                </div>
            </div>

        </div>

        <div class="elect-bottom-toolbar-backdrop"></div>   @* this is good here, leave it! *@

        <div class="ballot-contest" id="renderBodyWrapper">
            @RenderBody()
        </div>

    </div>
</div>


    @*<div class="ballot-contest" id="renderBodyWrapper">
        @RenderBody()
    </div>*@



    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>

VotingSite/VotingSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link id="favicon" rel="icon" type="image/x-icon" href="">
    <title>@ViewBag.Title - Voter Login</title>

    @Styles.Render("~/Content/loginPage") @* replaces the /css bundle *@
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>

    <div id="loginPageWrapper" class="d-flex view-container">
        <div class="elect-toolbar top">
            @* Cannot find a class called top in all of the EC code. -SKF 5/13/19 *@



            <div class="toolbar-background"></div>
            <div class="toolbar-content">

                @* Page Content *@
                <div class="election-info">
                    <div class="election-title">

                        <div class="logo"></div>
                        <div class="name">@Model.ElectionName</div>
                    </div>
                </div>

                <div class="elect-actions">
                    <div class="elect-action">
                        <a class="action-button">
                            <img src="~/Content/icons/action/settings.svg" class="elect-action-icon n-mobile" alt="Gear Icon" />
                            <img src="~/Content/icons/action/settings-wh.svg" class="elect-action-icon mobile" alt="Gear Icon" />
                            <span class="action-text">Settings</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="loginPageWrapper">
            @RenderBody()
        </div>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>